CALCULATOR = notification_message
VENDOR = aupera
include VERSION.mk

INCLUDE_SEARCH_DIRS += -I../../dependencies/include
LDLIBS += -lssl -lcrypto

include $(STAGING_DIR)/opt/aupera/make/Calculator.mk